# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/logistics/','/hackaton/','/automation/','/team/','/schedule/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "Devfest Rio de Janeiro 2017"
email: "rio.gdg@gmail.com"
description: "GDG DevFest é um evento que acontece durante todo ano pelo mundo inteiro com foco em falar sobre novas tecnologias que envolvem software e tecnologias relacionadas ao Google."
baseurl: "/devfest"
url: "https://gdgrio.github.io"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"
mapsApiKey: "AIzaSyDZNwTj3KQ6v27Mll8QmK5BrhT7nJOXe9U"

# Organizer Info
organizerName: "GDG Rio de Janeiro"
organizerAlternateName: "Google Developer Group Rio de Janeiro"
organizerDescription: "Comunidade aberta e voluntária que cria e compartilha experiências sobre o Google."
organizerEmail: "rio.gdg@gmail.com"
organizerLogo: "/img/seo/logo-gdg-rio.png"
organizerLink: "https://gdgrio.github.io/page/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@GDGRio"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://goo.gl/forms/vCmFNvTTfoMflFVR2"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/speakers/", text: "Palestrantes"}
 - {permalink: "/schedule/", text: "Agenda"}
bottomNavigationLinks:
 #- {link: "https://goo.gl/forms/vCmFNvTTfoMflFVR2", text: "Call4Papers"}
rightNavigationButtons:
 #- {link: "https://goo.gl/forms/vCmFNvTTfoMflFVR2", text: "Call4Papers"}

# Hero Block
heroImage: "1920x1080.png"
heroTitle: "GDG DevFest <typeout> 2017"
eventDate: "25 de Novembro de 2017 - 09h às 18h"
typeoutTextValues: '"", "Rio de Janeiro", "Duque de Caxias", "Petropólis", "Três Rios"'
typeoutFallback: "Rio de Janeiro"
heroButtons:
 #- {link: "https://goo.gl/forms/vCmFNvTTfoMflFVR2", text: "Call4Papers"}
 - {permalink: "/#tickets", text: "Ingressos"}

# About Block
aboutTitle: "Sobre o DevFest Rio de Janeiro"
aboutBlock:
 - {title: "Conferência", image: "conference.jpg", text: "O maior evento de tecnologia do Google no Rio de Janeiro, feito com carinho pela comunidade do GDG RJ." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "participantes", detail: "de todo Brasil"}
 - {count: "8", specialCharacter: "+", info: "horas", detail: "de pura tecnologia"}
 - {count: "20", specialCharacter: "+", info: "palestrantes", detail: "do país e do mundo"}
 - {count: "2", specialCharacter: "", info: "trilhas", detail: "mais o networking no lounge e coffee break"}

# Latest News Block
latestNewsTitle: ""

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Palestrantes"
rockstarSpeakersButtonText: "Veja todos os palestrantes"

# Location Block
locationBlockTitle: "Local"
eventLocationName: "Centro de Convenções SulAmérica"
eventLocationLink: "http://www.ccsulamerica.com.br/"
eventStreetAddress: "Av. Paulo de Frontin, 1"
eventAddressLocality: "Rio de Janeiro"
eventAddressLocalityRegion: "Cidade Nova"
eventPostalCode: "20260-010"
eventAddressCountry: "Brazil"
eventStartTime: "2017-11-25T09:00"
eventDoorTime: "09:00"
eventEndTime: "2017-11-25T19:00"
eventPlaceCoordinates: "-22.912485, -43.209320"
mapCenterCoordinates: "-22.912485, -43.209320"
mapMobileCenterCoordinates: "-22.912485, -43.209320"

# Venue Block
venueBlockTitle: "Espaço"
venueBigImage: "sulamerica_0.jpg"
venueSmallImage1: "sulamerica_1.png"
venueSmallImage2: "sulamerica_3.jpg"
venueSmallImage3: "sulamerica_4.jpg"
venueTitle: "Auditório Principal"
venueFeatures: ["Localizado no centro da cidade."]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "Venha compartilhar conhecimento conosco!"
twitterHashTag: "devfestrio"
twitterFeed: ""

# Partners Block
organizersTitle: "Organizadores"
partnersTitle: "Patrocinadores"
partnersC4sponsorsButton: "Seja um patrocinador"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Fique por dentro de notícias do GDG Rio de Janeiro"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Ingressos"
ticketsInfo: "Os ingressos dão acesso a todos a seções da conferência e coffee. Acomodação NÃO está inclusa no valor do ingresso."
ticketsOffers:
  -
    name: "1° Lote(Sem Camisa)"
    price: "30"
    priceCurrency: "R$"
    ticketsNumber: "60"
    ribbon: ""
    buyButtonLink: "https://www.sympla.com.br/devfest-rio-de-janeiro-2017__204453"
    buyButtonText: "Compre Agora"
    ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
    validFrom: "2017-10-18T12:00"
    validThrough: "2017-10-29T00:00"
    soldOut: true


  -
    name: "1° Lote(Com Camisa)"
    price: "60"
    priceCurrency: "R$"
    ticketsNumber: "60"
    ribbon: ""
    buyButtonLink: "https://www.sympla.com.br/devfest-rio-de-janeiro-2017__204453"
    buyButtonText: "Compre Agora"
    ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
    soldOut: true

  -
    name: "2° Lote(Sem Camisa)"
    price: "40"
    priceCurrency: "R$"
    ticketsNumber: "80"
    ribbon: ""
    buyButtonLink: "https://www.sympla.com.br/devfest-rio-de-janeiro-2017__204453"
    buyButtonText: "Compre Agora"
    ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
    disabled: false

  -
    name: "2° Lote(Com Camisa)"
    price: "80"
    priceCurrency: "R$"
    ticketsNumber: "80"
    ribbon: ""
    buyButtonLink: "https://www.sympla.com.br/devfest-rio-de-janeiro-2017__204453"
    buyButtonText: "Compre Agora"
    ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]


# Footer
socialLinks:
 - {link: "https://plus.google.com/u/0/+GDGRiodeJaneiroOficial", icon: "google-plus"}
 - {link: "https://twitter.com/GDGRio", icon: "twitter"}
 - {link: "https://www.facebook.com/GDGRio/", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://gdgrio.github.io/page/", text: "GDG Website"}
   - {link: "https://www.meetup.com/GDGRioDeJaneiro/", text: "GDG Meetup"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contatos"
  links:
   - {link: "mailto:rio.gdg@gmail.com", text: "rio.gdg@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "Sobre Nós"
aboutUs: "Desenvolvedores e amantes de tecnologia que estão sempre buscando compartilhar conhecimento junto com a comunidade. E também de reunir outras pessoas que partilham do mesmo interesse para conversar e trocar ideias e experiências."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
